# Add your code below
version: "3.1"

services:
  hyper-service:
    build: {'context': '.', 'dockerfile': 'Dockerfile'}
    image: task-manager-app:latest
    container_name: "task-manager-app"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_HOST_NAME: "mongodb"
      MONGO_PORT_NUMBER: 27017
    env_file: ['.env']
    depends_on: ['mongodb']
    networks:
     - task-manager-network
    ports:
      - "8000:8000"

  mongodb:
    image: mongo:6.0.8
    container_name: "task-manager-db"
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    env_file: ['.env']
    volumes:
      - task-manager-data:/data/db
    networks:
      - task-manager-network

volumes:
  task-manager-data:

networks:
  task-manager-network: